### ISSUE TITLE
Change color after password is cleared

### ISSUE THREAD

**Issue by travankor** [ifreund/waylock#11]
When the password is cleared, `waylock` should change the screen color back to the initial color.

This is useful after a failed login, to signal that the wrong password is cleared.

**Comment by ifreund** [comment]
I think that maintaining the "fail" color indefinitely is a kind of security feature, as it indicates that someone has attempted to login while you were away from your computer.

However that may be a little paranoid in practice, so I could see putting that "one way" behavior behind a `--one-way` flag.

**Comment by travankor** [comment]
`Waylock` could switch to the "input" color screen. This way you would know that someone has inputed to the computer. I think if you are paranoid, either "input" or "fail" should cause concern (if no one has touched your computer, then you should expect the "init" screen).

For example, someone could try to switch VTs with waylock and see if you have any open/ try to guess the login password (of any user not the current one). Once they finish, they will switch back to the waylock screen. Waylock will only display "input" and not "fail". So, I'm not sure if the current behavior is necessarily correct from a security perspective.

Alternatively, if the screen could just flash briefly (or switch colors) and return to "fail" once the password is reset, that would be enough for me.

**Comment by ifreund** [comment]
I've decided that making the behavior you described default is the way to go.  I am keeping the current behavior behind a new `--one-way` flag for the paranoid though.
