### ISSUE TITLE
Consider ini

### ISSUE THREAD

**Issue by travankor** [ifreund/waylock#14]
While toml is an excellent format, waylock's configuration is very simple and doesn't make use of a lot of toml features. Ini is (visually) similar to toml , but a lot less complex and smaller code (and binary)-wise.

Additionally, I think ini allows values with the # sign, while this is not allowed in toml. So this change would make the config file more consistent with the CLI.

**Comment by ifreund** [comment]
I'm not a huge fan of ini personally, but could possibly be persuaded otherwise given hard data on exactly how much it would shrink the binary by.  Keep in mind that I'm more focused on robustness than minimalism when it comes to the code base of this project, and i believe toml fits that ideal better than ini which lacks strong typing and is loosely defined.

In ini, usually everything is a string, so # is allowed, but some implementations use # for comments which could be confusing. Note that toml allows for example
```toml
[colors]
init_color = "#002b36"
```
which waylock currently does not except, though I would certainly merge a PR implementing support for that.

**Comment by travankor** [comment]
The binary size should shrink by ~100KiB. You're right that toml has stronger typing and an actual specification, but right now waylock only has four options and a flat hierarchy. This could change if waylock adds more features and options (not sure what the roadmap is).

Another note, rust-ini does not support serde, so there would need to be some manual logic for that.

**Comment by ifreund** [comment]
So ~100KiB is about 2% of the current 4.3MiB, which I don't think is significant enough to motivate a switch on it's own.

There are certainly more features I'd like to add to waylock, in particular the ability to act as a limited wayland kiosk and use any arbitrary wayland program to supply the graphics for the lock screen.  However that is non-trivial to implement and I'm currently spending most of my time on [river](https://github.com/ifreund/river).

So, I guess I'm inclined to stick with toml for the foreseeable future.

**Comment by travankor** [comment]
>So ~100KiB is about 2% of the current 4.3MiB, which I don't think is significant enough to motivate a switch on its own.

The current size of a release build for me is 1.5 MiB, so ~100KiB is somewhere between 5-10%. I guess that the absolute reduction would be larger if debug symbols are included.

>There are certainly more features I'd like to add to waylock, in particular the ability to act as a limited wayland kiosk and use any arbitrary wayland program to supply the graphics for the lock screen.

This sounds good and you should absolutely stick with toml in this case. I would probably drop the suckless reference not to confuse anyone, though. Suckless is definitely about minimizing binary size, at the cost of, well, everything.

Another idea that I think would be nice is extra security mechanisms. For example, on an incorrect attempt, take a picture with a camera through a shell script or lua interface.

>I'm currently spending most of my time on river.

Nice, that looks very neat. After spending a lot of time tinkering with both the sway config and i3 IPC, I am still not happy with my experience with sway, due to how badly/arbitrarily i3 is designed IMO. That said, I used to like herbstluftwm in X11 land, specifically the concept of separating frames from the application. (Interestingly enough, bspwm is a fork of hersbtluftwm, which is where they got the socket idea from, but dropped the use of frames).

**Comment by ifreund** [comment]
> The current size of a release build for me is 1.5 MiB, so ~100KiB is somewhere between 5-10%. I guess that the absolute reduction would be larger if debug symbols are included.

Aye, I was measuring a release build prior to running `strip.

> I would probably drop the suckless reference not to confuse anyone, though. Suckless is definitely about minimizing binary size, at the cost of, well, everything.

Fair enough, I'll do this next time I add a feature.

> Another idea that I think would be nice is extra security mechanisms. For example, on an incorrect attempt, take a picture with a camera through a shell script or lua interface.

Adding a hook to run a shell script on failure is a great idea.  Could also be used to log, send a email, play an alarm sound, etc.

> After spending a lot of time tinkering with both the sway config and i3 IPC, I am still not happy with my experience with sway, due to how badly/arbitrarily i3 is designed IMO.

Agree with you there, I love sway and everything it's done for the wayland community, but I really can't stand the design of i3. Hence, I am writing my own compositor.  I've never used herbstluftwm, sounds like I should check it out though.
