### ISSUE TITLE
feature: handle Control-U keyboard shortcut like readline, etc

### ISSUE THREAD

**Issue by jokeyrhyme** [ifreund/waylock#26]
Howdie,

Thanks so much for sharing this screen lock solution

I have developed a muscle-memory for hitting Control-U to erase what I've typed to start again, such as when I know when I've mistyped my password

I believe this convention was established with readline or perhaps emacs: https://tiswww.case.edu/php/chet/readline/rluserman.html#SEC17

> unix-line-discard (C-u)
>    Kill backward from the cursor to the beginning of the current line.

So, it works this way in bash, zsh, etc

And I've noticed this keyboard shortcut is implemented in various non-readline places includes Bitwarden, Google sign-in, Idaptive sign-in, [`swaylock`](https://github.com/swaywm/swaylock/blob/235b925df7e1bb82d98f1ac8c02e8f85d0a54ee9/password.c#L149-L156), probably more

Is this the sort of thing you'd accept a pull request for?

Cheers!

**Comment by ifreund** [comment]
See #28 for the current state of the project.

I will likely implement this in the next version of waylock though as it is the most common feature request.

**Comment by ifreund** [comment]
Implemented in  #39
