### ISSUE TITLE
waylock is currently feature-frozen

### ISSUE THREAD

**Issue by ifreund** [ifreund/waylock#28]
I currently consider waylock feature complete and do not intend to accept any new features at this time. Bug reports and bugfixes are of course welcome, though it's been over 6 months so far without any. 

I do intend to resume active development on this project at some point in the future when it becomes more clear what the best way to do actually secure screenlocking on wayland is. I'll probably end up rewriting waylock in zig at that point as well in order to handle OOM properly and simplify things.

**Comment by ifreund** [comment]
Update on this, I've been working on a better, more secure protocol for screenlocking which will hopefully be accepted into wayland-protocols in the next month or so: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/131

**Comment by savchenko** [comment]
Judging from Simon's comments, it will be inevitably merged (congrats!). Do you plan to implement it in "Waylock v2"?

**Comment by ifreund** [comment]
> Judging from Simon's comments, it will be inevitably merged (congrats!). Do you plan to implement it in "Waylock v2"?

Yes of course, though it may take me a bit to find the time.

**Comment by ifreund** [comment]
Waylock has now been rewritten and supports a minimum viable feature set, not yet including configuration. Exactly what configuration options will be re implemented is yet to be decided.

**Comment by niksingh710** [comment]
is waylock planning to get some features ? 
don't want much just a clock and background image ?

**Comment by Leon-Plickat** [comment]
A clock requires either text rendering for a digital clock, which commonly pulls heavy dependencies, or some pixel manipulation / drawing library for an analog clock. That may not be wanted for a simple screen-locker.

Instead, it may be a better design to allow other clients (like my own wlclock) to draw over  the lock screen, likely via a dedicated protocol extension. I actually have a [design for such a protocol extension](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/134), I just did not have the time yet to get it merged. When the session lock protocol gets a bit more mainstream and this usecase gets more often requested, it should be  a bit easier to get it merged and I'll probably return to it.

**Comment by niksingh710** [comment]
> A clock requires either text rendering for a digital clock, which commonly pulls heavy dependencies, or some pixel manipulation / drawing library for an analog clock. That may not be wanted for a simple screen-locker.
> 
> Instead, it may be a better design to allow other clients (like my own wlclock) to draw over the lock screen, likely via a dedicated protocol extension. I actually have a [design for such a protocol extension](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/134), I just did not have the time yet to get it merged. When the session lock protocol gets a bit more mainstream and this usecase gets more often requested, it should be a bit easier to get it merged and I'll probably return to it.

Yeah that protocol seems to open more possibilities. Like having notification and other stuff as desired.

**Comment by niksingh710** [comment]
Imo screen lock should give user a layer where user can draw stuff like using html css or gtkcss or any kindda stuff 


By this we can seprate the lock instance and the visual layer instance and their development seprate too.
