### ISSUE TITLE
Future simplification idea

### ISSUE THREAD

**Issue by divVerent** [ifreund/waylock#29]
An even simpler design would be interfacing with logind to switch to the greeter (sddm, gdm etc.). Then waylock wouldn't contain any PAM code, but would just lock the screen "forever".

This would then result in two processes:

- waylock-idle: watches for idle time (similar to swayidle), then sends a lock notification to logind (to which the system will switch to the greeter login prompt). Also listens to logind notifications for locking and spawns waylock, and kills waylock when there's a logind unlock notification. At first this can be just a shell script launching swayidle with appropriate parameters, but may be worth doing in a simpler way. Could actually be two separate processes, one using Wayland for the idle timer, and a separate one just interacting with logind.
- waylock: a PAM-less locker. Just blanks the screen and drops all input. Has basically no chance of dying.

Mainly writing this down for myself as I know this project is frozen and this would be a strongly breaking change - I may actually end up forking this repo and ripping out all the PAM parts, all the drawing parts, to just leave the locking itself.

But mainly wondering - is there maybe already an existing project doing this? I am looking for a _reliable_ Wayland locker and haven't found any yet - they all e.g. die if the PAM module crashes, which is likely what led to swaylock getting kicked out of Debian and jwz telling us all "told you so".

**Comment by ifreund** [comment]
@divVerent I'm solving the protocol issue: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/131
