### ISSUE TITLE
Dispatch for object wl_shm@4 errored.

### ISSUE THREAD

**Issue by demostanis** [ifreund/waylock#32]
Running under Wayfire 0.8.0-6720f6a6 (Dec 11 2021, branch 'makepkg')
`waylock` with no arguments errors out with `Dispatch for object wl_shm@4 errored.`.
strace attached.
[strace.txt](https://github.com/ifreund/waylock/files/7697780/strace.txt)

**Comment by ifreund** [comment]
This seems to be have been fixed by updating the SCTK dependency, probably was a bug in SCTK or wayland-rs. Waylock 0.3.4 has been released including this change.
