### ISSUE TITLE
waylock not compatible with wlroots 0.15.0

### ISSUE THREAD

**Issue by dvzrv** [ifreund/waylock#33]
Hi! It looks as if waylock might not be compatible with wlroots 0.15.0.

On Arch we have just updated to that wlroots version (including rebuilds for the depending packages, e.g. sway 1.7).

Upon `setsid -f waylock` I now get: `Error: Os { code: 71, kind: Other, message: "Protocol error" }`

**Comment by ifreund** [comment]
Just fixed this and tagged waylock 0.3.4, I've been using swaylock with the new more secure `ext-session-lock-v1` protocol until I finish rewriting waylock so I didn't notice.
