### ISSUE TITLE
Please provide a security statement

### ISSUE THREAD

**Issue by markstos** [ifreund/waylock#35]
As a security product, it would be helpful for potential users to evaluate if `waylock` will need their personal security requirements if there was a statement about the security design and known security issues. 

As an example, Google's `xsecurelock` provides a such statement on the security design and known security issues: 

https://github.com/google/xsecurelock#security-design

Thanks.

**Comment by ifreund** [comment]
Right now waylock is not secure. Once `ext-session-lock-v1` is implemented it will be. X11 screen locking is not secure and never will be.
