### ISSUE TITLE
waylock won't password-protect if launched from a piped menu (example attached)

### ISSUE THREAD

**Issue by manfred3000** [ifreund/waylock#37]
OS: Arch Linux
WM: wlroots-based (`wayfire sway`)
`waylock`:  0.3.5

The screen can be unlocked by simply pressing `Enter` in the following use-case:
```
#!/bin/sh

case "$(printf "Lock the screen" | fuzzel -d)" in
        Lock\ the\ screen) waylock ;;
esac
```
Not sure whether this is a "bug", or if `waylock` isn't supposed to be launched as shown in the script above.

Any ideas are appreciated,
thanks

**Comment by ifreund** [comment]
I can't reproduce this though running waylock using your script under river or sway 1.7.

Perhaps setting `WAYLAND_DEBUG=1` in the environment and running waylock with `-vvvv` would tell us more, I'm very confused why running waylock from a script in your example should matter at all though.

That said, I probably won't fix this as I'm nearly finished rewriting waylock to be much simpler and more secure (see the [next](https://github.com/ifreund/waylock/tree/next) branch). I don't consider the rust version you see on master branch to be secure, no client side wayland screenlockers not using the `ext-session-lock-v1` are. The rust code also suffers heavily from abstraction and accidental complexity.

**Comment by ifreund** [comment]
Oh, there is one bug I've fixed on the `next` branch but not in the rust version that could explain this. To quote the commit message:
> If the wayland server's write buffer for a client connection fills up, it terminates the client. Since authentication using PAM is blocking, this can happen fairly easily if e.g. many input events are triggered during authentication. As such, we must make this authentication asynchronous.

This isn't handled properly on master branch and won't be as I'd rather devote my time to finishing up the far better implementation.

**Comment by manfred3000** [comment]
I actually just tried the script on a different machine and cannot reproduce the issue there, either (the issue occurs on an old Intel Atom laptop with the "same" basic setup).

I will try and build `waylock`-next and report back later.
I'm closing this for now.

Thanks for your time and explanation!

**Comment by ifreund** [comment]
> I will try and build `waylock`-next and report back later.

Note that no compositor other than river with this PR currently supports ext-session-lock-v1 as far as I'm aware: https://github.com/riverwm/river/pull/497

I'd recommend waiting until I merge `next` into master, this should happen in the next few days hopefully.

**Comment by manfred3000** [comment]
I just tried `swaylock` and the same issue occurs - so nothing to worry about the code in that regard...
Sorry for the noise :)

**Comment by ifreund** [comment]
No worries!
