### ISSUE TITLE
building waylock

### ISSUE THREAD

**Issue by curz46** [ifreund/waylock#43]
Hi, thanks for your efforts on this project. It's very sleek, I was surprised to see it's written in Zig!

I'm planning to have a stab at a fun fork, drawing a matrix-esque animated wallpaper in place of the lock screen. 

The packaged binary on arch repos works fine, but when building it manually I get this error. I installed it as suggested in `README` under `/usr`. Do you know why this might be?

```
$ waylock
error: ext_session_lock_manager_v1 not advertised
error: failed to read password from pipe: EndOfStream
```

If relevant, the contents of the `pam.d/waylock` file:

```
auth include system-auth
```

**Comment by Leon-Plickat** [comment]
The package you installed from the repo likely still is the old, pre-rewrite version of waylock.

Waylock master branch, unlike the old version, needs the session lock protocol extension. This is apparently not yet supported by your compositor.

**Comment by curz46** [comment]
Ah, that makes sense. Thanks for the help, I will look into that.

FYI the compositor I'm using is sway. Shame it's not supported yet.
