### ISSUE TITLE
Waylock doesn't start 

### ISSUE THREAD

**Issue by SkelyTony** [ifreund/waylock#44]
Distro: Alpine linux
running waylock puts out the following output:

error: ext_session_lock_manager_v1 not advertised
error: failed to read password from pipe: EndOfStream

**Comment by ifreund** [comment]
Waylock 0.4 only supports compositors implementing `ext-session-lock-v1`, which is afaik currently only river with [this PR](https://github.com/riverwm/river/pull/497) or the master branch of sway. Merging the river PR is blocked on a wlroots 0.16 release which I expected to be tagged months ago.
