### ISSUE TITLE
crash on wrong password + red screen persists

### ISSUE THREAD

**Issue by p00f** [ifreund/waylock#45]
(This was discussed on IRC in the river room)
When a wrong password is entered and then the correct one, the red screen stays even after waylock crashes.

I'm using systemd-homed.

waylock log with `WAYLAND_DEBUG=1` : https://paste.sr.ht/~p00f/cd0eb1aa9826f7a45eae176a82bc96ec7e560fc8

coredump backtrace: https://paste.sr.ht/~p00f/1d8058d0728285c5950b949667c88cf9c9ed93e9

core file:
[core.waylock.60254.d4f4a1c35bc54ba5ae9990bee8274345.34752.1664377262000000.tar.gz](https://github.com/ifreund/waylock/files/9671217/core.waylock.60254.d4f4a1c35bc54ba5ae9990bee8274345.34752.1664377262000000.tar.gz)

**Comment by ifreund** [comment]
Thanks for the stack trace, after reading the related PAM code I think this should be fixed by c83399292655a04c11cba11680f458fed575bf14.

**Comment by p00f** [comment]
Yes, thanks!
