### ISSUE TITLE
[feature] allow image and text fill

### ISSUE THREAD

**Issue by eqn-group** [ifreund/waylock#46]
Hello, 
please take a look at swaylock or swaylock-effects and atleast allow some options like:
1- https://github.com/lokesh-krishna/dotfiles/blob/main/tokyo-night/config/swaylock/config
2- https://github.com/lokesh-krishna/dotfiles/blob/main/nord-v2/bin/lock.sh

I would love to use your tool, its better.

**Comment by ifreund** [comment]
I'm not currently planning on extending the feature set of waylock.
