### ISSUE TITLE
Screenshot in readme

### ISSUE THREAD

**Issue by yavko** [ifreund/waylock#52]
Would be nice to know how it looks before using it

**Comment by Borlaag** [comment]
I am not a maintainer, but a happy user. `waylock` is a very minimal screen locker. 

There are three configuration options, `-init-color`, `-input-color`, and `-fail-color`. The first is the initial color, the second is the color the screen changes to when the user starts typing their password, and the third is the color the screen changes to when the user hits `enter` after inputting an incorrect password.

The screenshots would essentially just be solid colors, so not super useful IMO! If you're keen on trying it out, you don't actually have to set it as your default screen locker - you can install it and run it from the command line to give it a try!

**Comment by yavko** [comment]
> I am not a maintainer, but a happy user. `waylock` is a very minimal screen locker.
> 
> There are three configuration options, `-init-color`, `-input-color`, and `-fail-color`. The first is the initial color, the second is the color the screen changes to when the user starts typing their password, and the third is the color the screen changes to when the user hits `enter` after inputting an incorrect password.
> 
> The screenshots would essentially just be solid colors, so not super useful IMO! If you're keen on trying it out, you don't actually have to set it as your default screen locker - you can install it and run it from the command line to give it a try!

Ah thanks for clarifying, it would at least be nice if that was clarified in the readme!
