### ISSUE TITLE
Tutorial on how to set up waylock+river on laptop?

### ISSUE THREAD

**Issue by fritzrehde** [ifreund/waylock#57]
Hi, I was wondering if someone had a link to a good tutorial on how to set up `waylock` with `river` on a laptop. I would like to run `waylock` automatically when I close the lid of my laptop (though the screen should obviously be turned off in the closed state). The reason I am filing this as an issue is because I believe most people using `waylock` will be in a similar situation, and adding some documentation on how to do this to the readme would be quite helpful. Thanks!

**Comment by Leon-Plickat** [comment]
Use the `map-switch` command in river.

**Comment by fritzrehde** [comment]
I can see the `map-switch` command in the river man page, but I don't quite understand how it helps me activate `waylock` when I close the laptop lid. If you have the same use-case, do you have a link to your river config shell script (or whatever you use to invoke `waylock`)?

**Comment by fritzrehde** [comment]
After some web browsing, I found `swayidle`. Is this the recommended tool to do what I want?

**Comment by Leon-Plickat** [comment]
`map-switch` allows you to map river commands to the laptop lid switch. One possible command you can map is `spawn`, which you can use to start waylock. Swayidle has a slightly different use case: it could be used to launch waylock after a configured amount of inactivity.

```
riverctl map-switch normal lid close spawn waylock
```

**Comment by fritzrehde** [comment]
Oh wow, that was incredibly easy! No cumbersome systemd stuff! Thanks a lot for your help! This is awesome!

**Comment by Leon-Plickat** [comment]
There is actually good chance systemd logind may get in your way.

You can turn that off in `/etc/systemd/logind.conf`. Put a `HandleLidSwitch=ignore` in the `[Login]` section.

**Comment by fritzrehde** [comment]
What exactly do you mean with "get in your way" and "turn *that* off". I added the line you sent to my config, and now, when I open my laptop after closing it, `swaylock` prompts me for my password.

**Comment by Leon-Plickat** [comment]
On some distributions, logind is setup by default to enter sleep mode when the lid is closed. That may or may not be what you want and has a slight chance of messing with for example lid switch maps.

**Comment by fritzrehde** [comment]
Ok, in my case I want the device to go into sleep mode. What would the laptop do when the lid is closed given your `HandleLidSwitch=ignore`? Does it still go to sleep or stay on somehow?

**Comment by Leon-Plickat** [comment]
It would make logind completely ignore the lid switch, so it would do nothing when you close the lid.

**Comment by fritzrehde** [comment]
Ok. Another question: Can I set a max amount of time after which I want the laptop to go to sleep even when open (e.g. a few minutes)? How would I make sure `waylock` is called then?

**Comment by Leon-Plickat** [comment]
Yes, that's what swayidle is for. It has a config file where you could for example put something like this:

```
timeout 300 "systemctl suspend"
before-sleep "waylock -fork-on-lock"
```

**Comment by fritzrehde** [comment]
Why do I need `-fork-on-lock` for waylock there (and not in the `riverctl` config from earlier)?

**Comment by Leon-Plickat** [comment]
Because normally the waylock command only returns once the screen has been unlocked. However, sayidle delays the locking until after the command has returned (this is to make sure the screen gets locked _before_ the computer entering sleep mode). `-fork-on-lock` does exactly what it says: It tries to lock the screen as normal and should that be successful, fork itself into the background, so that the waylock process called by swayidle can return and thus allowing logind to enter sleep mode. These things are explained in the respective man pages.
