### ISSUE TITLE
Can't use backspace when unlocking?

### ISSUE THREAD

**Issue by chadkouse** [ifreund/waylock#60]
Seems like when I'm entering my password to unlock if I use backspace it doesn't actually work so if I know I made a mistake on my password then I basically have to just press enter and wait for it to reset

**Comment by ifreund** [comment]
From the man page:

> to clear what you've typed press Esc or Ctrl-U.

I didn't bother implementing backspace because it would require waylock to become unicode aware.

**Comment by ifreund** [comment]
No worries!
