### ISSUE TITLE
Waylock freezing backlight status

### ISSUE THREAD

**Issue by UltraBlackLinux** [ifreund/waylock#61]
Hey there,
I'm currently working on making my Linux installation more mobile-friendly. I have already set most things up, but there is one more Issue I'm facing: Waylock will freeze the backlight status once opened.
Meaning, that is I open waylock and afterwards try to lower the screen brightness via `/sys/class/backlight/brightness` it will not change. If I open waylock with already lowered brightness, waylock will yet again freeze that and the change will only be visible after unlocking.
Is there a way around this?
Thanks!

**Comment by Leon-Plickat** [comment]
Are you sure it's not just your keybinds that simply do not work while the screen is locked?

**Comment by UltraBlackLinux** [comment]
I don't think so. I overwrote the powerbutton behavior with acpi and set it to use a script.

If I disable the backlight before locking, the screen stays black even after pressing the pb until waylock is unlocked after which the screen will either turn on or turn on after pressing the pb, depending on what was done before.

What I just noticed writing this reply, is that waylock was blocking the backlight script until it was closed, so disabling the screen after locking would not work without running that in the background. I should have noticed that earlier.

I'm still confused about the weird backlight behavior when disabling it first.

**Comment by ifreund** [comment]
Sharing the exact script you use would be helpful to understand what is happening here. 

In any case, this is almost certainly an issue with whatever compositor you are using rather than with waylock itself. You could confirm that by testing with swaylock as well or a different compositor. Waylock itself does interact with the power management of monitors at all.

**Comment by UltraBlackLinux** [comment]
Well the relevant part of the script is this iirc:
```bash
echo 0 > /sys/class/backlight/brightness
su myuser -c 'XDG_RUNTIME_DIR=/run/user/1000 waylock'
```
Changing the position of the `echo` matters, and the behavior changes if I run waylock in the background and then set the backlight

**Comment by ifreund** [comment]
There is still no information provided about the compositor being used, I'm quite confident that waylock is not at fault here and you would be better off opening a bug report upstream with that compositor.

Testing with swaylock as well would also be useful.

**Comment by UltraBlackLinux** [comment]
oh sorry I missed the compositor part. I was using  Hyprland during my testing.

I'm not gonna test swaylock because I'm quite happy now, with the setup working fine.
