### ISSUE TITLE
Screen Saver Wont Show

### ISSUE THREAD

**Issue by djfhsdkjfsj** [ifreund/waylock#67]
I have an issue with waylock 

Error
''
advertised wl_output version too old, version 3 required
error: failed to read password from pipe: EndOfStream
''

I dont know what the error means my system is fully updated

System is Arch linux Intel Celeron N3160

**Comment by djfhsdkjfsj** [comment]
im running cinnamon with wayland

**Comment by ifreund** [comment]
It means that your compositor (cinnamon I guess) does not support the wayland interfaces waylock requires.
