### ISSUE TITLE
When using labwc with waylock if I turn the monitor off when I turn it back on I lose all keyboard input

### ISSUE THREAD

**Issue by charbelnicolas** [ifreund/waylock#69]
Hello, I don't know if this is an issue with waylock or labwc [https://github.com/labwc/labwc/](https://github.com/labwc/labwc/) but as the title says, if I lock the session with waylock and then turn of my monitor, when I turn it back on I can't use my keyboard at all and I have to restart my computer.

I tried doing the same with swaylock and it works, I am still able to unlock my session, so this is something that only happens with waylock.

I also raised an issue in labwc's github: [https://github.com/labwc/labwc/issues/1369](https://github.com/labwc/labwc/issues/1369)

I prefer using waylock for its simplicity instead of swaylock but this makes it unusable for me when using labwc.

Any help is appreciated!

**Comment by ifreund** [comment]
This is likely a bug with labwc, a WAYLAND_DEBUG=1 log of this happening would likely tell us for sure.

**Comment by ifreund** [comment]
Actually, I think dfb53fa3109b451a1d99e279d5640e8413d1b085 should fix this, let me know if it doesn't, I haven't tested under lawbc specifically

**Comment by ifreund** [comment]
Looks like this did fix the issue under labwc, I'll tag a new release shortly

**Comment by charbelnicolas** [comment]
I'm so glad to hear that! Thank you! Yay!
